language: ruby
cache: bundler
rvm:
- 1.9.3
- 2.0.0
- 2.1.7
- 2.2.3
- ruby-head
git:
  depth: 1
before_install: gem install bundler
script:
- bundle exec rake
add_ons:
  code_climate:
    repo_token:
      secure: EAwZHn/4SsBkzTjspwmkSCdPkaNbHe4fNcfwo6EBYPxmQGuIZuAGVtZ7mNYyZMC55zjivxpmDI7dFtXOhN05eY0O6MYvvDNr4qxnGrr3njLxWz/vo5+ebEWhujjnFcZI7BzgaILFWv22Eu9fRM3DsEcIKL/2hvyhSWlhJEeSAqb5EiszoYBHq5hH5NNK5oGfPZ2UWi66Eo/7ukN4XqVkhrw2Xek8wqNAukVYIPyQSV2v/wOG+q9apdFKJ6HZv+l9mt9uCz+WmGrPzpu3u7zvBiBzs6d5Eom2StQFqBK0vUzU4thtQop0iRFeCfMuK0ZLOWkYSe5Y0fQdRNJm6neJFn5c4PIXyxq0S4vhknj5qHaMoiL8GwdXgld01bg5DbskRbAIaA/BYEF4y9k2TE2UZj0Zv8jnBtZYgGsetluks32IF6A40Gq9pRd5Lu56Ddru9NskJTOrRFiXhSQ0sFsaHUlxNep+Qzm+SBkukRHuZHIQhrwd0YQiGTEkX2Zg1xOT2VFzBk6Nv6fdun4DQ1nTZMSv6rN8MPbpflJWlZeee5v6uT67f6PDbLZZac9Hbe8ovtO7J2o7FmoV0IekTDYjrMIlVq3jY2qHsrIW5dT3KPNHOscXlk/qDI28XM6/AEeSWpTREc1aJrveW9yy68qgT5SXCJt2YvGv7fS2LDzxVeM=
